name: Run tests

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - '**.ipynb'

jobs:
  job_mytests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12"]
      fail-fast: true
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          init-shell: bash
          condarc: |
            channels:
              - conda-forge
            channel_priority: strict
          cache-environment: true

      - name: Install package (editable)
        shell: bash -l {0}
        run: |
          micromamba run -n gliderflightOG1 python -m pip install --upgrade pip
          micromamba run -n gliderflightOG1 python -m pip install -e . --no-deps --force-reinstall

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          micromamba run -n gliderflightOG1 pytest

# Use the below code after deploying a release
#    - name: Setup Micromamba Python ${{ matrix.python-version }}
#      uses: mamba-org/setup-micromamba@v2
#      with:
#        environment-name: TEST
#        init-shell: bash
#        create-args: >-
#          python=${{ matrix.python-version }} --file requirements-dev.txt --channel conda-forge



#    - name: Full Tests
#      run: |
#        python -m pytest --cov=seagliderOG1 --cov-report term-missing  tests/
